# See https://www.appveyor.com/docs/getting-started-with-appveyor-for-linux/
# Don't build branches with a PR, since their build will be created with the PR itself. 
# Otherwise there would be two builds -- one for the PR and one for the branch.
# If you're having issues with getting your PR to build, make sure there are no merge conflicts.
skip_branch_with_pr: true

# Enable 'Do not build on "Push" events' in the AppVeyor project settings
# to only build commits from pull requests
branches:
  only:
    - master

# Only run AppVeyor on commits that modify at least one of the following files
# Delete these lines to run AppVeyor on all master branch commits
only_commits:
  files:
    - .appveyor.yml
    - build/
    - ci/install.sh
    - content/

image: ubuntu
services:
  - docker

# Set SPELLCHECK to true to enable Pandoc spellchecking
environment:
  SPELLCHECK: false

install:
  # Create the message with the triggering commit before install so it is
  # available if the build fails
  - TRIGGERING_COMMIT=${APPVEYOR_PULL_REQUEST_HEAD_COMMIT:-APPVEYOR_REPO_COMMIT}
  - JOB_MESSAGE=" for commit $TRIGGERING_COMMIT "
  - source ci/install.sh

test_script:
  - bash build/build.sh
  - MANUSCRIPT_FILENAME=manuscript-$APPVEYOR_BUILD_VERSION-${TRIGGERING_COMMIT:0:7}
  - cp output/manuscript.html $MANUSCRIPT_FILENAME.html
  - cp output/manuscript.pdf $MANUSCRIPT_FILENAME.pdf
  - appveyor PushArtifact $MANUSCRIPT_FILENAME.html
  - appveyor PushArtifact $MANUSCRIPT_FILENAME.pdf
  - |
      if [ "${SPELLCHECK:-}" = "true" ]; then
        SPELLING_ERRORS_FILENAME=spelling-errors-$APPVEYOR_BUILD_VERSION-${TRIGGERING_COMMIT:0:7}.txt
        cp output/spelling-errors.txt $SPELLING_ERRORS_FILENAME
        appveyor PushArtifact $SPELLING_ERRORS_FILENAME
        SPELLING_ERROR_LOCATIONS_FILENAME=spelling-error-locations-$APPVEYOR_BUILD_VERSION-${TRIGGERING_COMMIT:0:7}.txt
        cp output/spelling-error-locations.txt $SPELLING_ERROR_LOCATIONS_FILENAME
        appveyor PushArtifact $SPELLING_ERROR_LOCATIONS_FILENAME
      fi

build: off

cache:
  - ci/cache

on_success:
  - echo "Artifacts available from $APPVEYOR_URL/project/$APPVEYOR_ACCOUNT_NAME/$APPVEYOR_PROJECT_SLUG/builds/$APPVEYOR_BUILD_ID/artifacts"
  - echo "Updated PDF available from $APPVEYOR_URL/api/buildjobs/$APPVEYOR_JOB_ID/artifacts/$MANUSCRIPT_FILENAME.pdf"
  - appveyor AddMessage "$JOB_MESSAGE is now complete."
  - |
      if [ "${SPELLCHECK:-}" = "true" ]; then
        SPELLING_ERROR_COUNT=($(wc -l $SPELLING_ERROR_LOCATIONS_FILENAME))
        appveyor AddMessage " <details><summary>Found $SPELLING_ERROR_COUNT potential spelling error(s). Preview:</summary>$(head -n 100 $SPELLING_ERROR_LOCATIONS_FILENAME)"
        appveyor AddMessage "... </details>"
      fi

on_failure:
  - appveyor AddMessage "$JOB_MESSAGE failed."

# The following lines can be safely deleted, which will disable AppVeyorBot
# notifications in GitHub pull requests
# Notifications use Mustache templates http://mustache.github.io/mustache.5.html
# See https://www.appveyor.com/docs/notifications/#customizing-message-template
# for available variables
notifications:
  - provider: GitHubPullRequest
    template: "AppVeyor [build {{buildVersion}}]({{buildUrl}})
      {{#jobs}}{{#messages}}{{{message}}}{{/messages}}{{/jobs}}
      {{#passed}}The rendered manuscript from this build is temporarily available for download at:\n\n
      {{#jobs}}{{#artifacts}}- [`{{fileName}}`]({{permalink}})\n{{/artifacts}}{{/jobs}}{{/passed}}"
