dist: trusty
sudo: false
language: generic
branches:
  only:
    - master
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-4.4.10-Linux-x86_64.sh
    --output-document miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source $HOME/miniconda/etc/profile.d/conda.sh
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda info --all
install:
  - conda env create --quiet --file build/environment.yml
  - conda activate manubot
script:
  - sh build/build.sh
cache:
  directories:
    - ci/cache
after_success:
  - test $TRAVIS_BRANCH = "master" &&
    test $TRAVIS_PULL_REQUEST = "false" &&
    sh ci/deploy.sh
