name: Manubot
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  manubot:
    name: Manubot
    runs-on: ubuntu-latest
    env:
      GITHUB_PULL_REQUEST_SHA: ${{ github.event.pull_request.head.sha }}
      SPELLCHECK: true
    steps:
      - name: Set Environment Variables
        run: |
          TRIGGERING_SHA=${GITHUB_PULL_REQUEST_SHA:-$GITHUB_SHA}
          echo "TRIGGERING_SHA_7=${TRIGGERING_SHA::7}" >> $GITHUB_ENV
          echo "TRIGGERING_SHA: $TRIGGERING_SHA"
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          # fetch entire commit history to support get_rootstock_commit
          fetch-depth: 0
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ci/cache
          key: ci-cache-${{ github.ref }}
          restore-keys: |
            ci-cache-refs/heads/master
      - name: Install Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: manubot
          environment-file: build/environment.yml
          auto-activate-base: false
          miniconda-version: 'latest'
      - name: Install Spellcheck
        shell: bash --login {0}
        run: |
          if [ "${SPELLCHECK:-}" = "true" ]; then
            bash ci/install-spellcheck.sh
          fi
      - name: Build Manuscript
        shell: bash --login {0}
        run: bash build/build.sh
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: manuscript-${{ github.run_id }}-${{ env.TRIGGERING_SHA_7 }}
          path: output
      - name: Deploy Manuscript
        if: github.ref == 'refs/heads/master' && github.event_name == 'push' && !github.event.repository.fork
        env:
          MANUBOT_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MANUBOT_SSH_PRIVATE_KEY: ${{ secrets.MANUBOT_SSH_PRIVATE_KEY }}
          CI_BUILD_WEB_URL: https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks
          CI_JOB_WEB_URL: https://github.com/${{ github.repository }}/runs/${{ github.run_id }}
        shell: bash --login {0}
        run: bash ci/deploy.sh
